//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyQuestionsConfigurator.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurveyQuestionsConfigurator.Entities.Resources.LanguageStrings", typeof(LanguageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this question?.
        /// </summary>
        public static string AreYouSureYouWantToDelete {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Connectivity.
        /// </summary>
        public static string Checkconnectivity {
            get {
                return ResourceManager.GetString("Checkconnectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed..
        /// </summary>
        public static string ConnectionFailedError {
            get {
                return ResourceManager.GetString("ConnectionFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name is required..
        /// </summary>
        public static string DatabaseNameRequired {
            get {
                return ResourceManager.GetString("DatabaseNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Value.
        /// </summary>
        public static string EndValue {
            get {
                return ResourceManager.GetString("EndValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Value Caption.
        /// </summary>
        public static string EndValueCaption {
            get {
                return ResourceManager.GetString("EndValueCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End value caption is required..
        /// </summary>
        public static string EndValueCaptionRequired {
            get {
                return ResourceManager.GetString("EndValueCaptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End value must be larger than start value..
        /// </summary>
        public static string EndValueError {
            get {
                return ResourceManager.GetString("EndValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End value is required..
        /// </summary>
        public static string EndValueRequired {
            get {
                return ResourceManager.GetString("EndValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Smiley Faces.
        /// </summary>
        public static string NumberOfSmileyFaces {
            get {
                return ResourceManager.GetString("NumberOfSmileyFaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of smiley faces field is required..
        /// </summary>
        public static string NumberOfSmileyFacesRequired {
            get {
                return ResourceManager.GetString("NumberOfSmileyFacesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Stars.
        /// </summary>
        public static string NumberOfStars {
            get {
                return ResourceManager.GetString("NumberOfStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of stars field is required..
        /// </summary>
        public static string NumberOfStarsRequired {
            get {
                return ResourceManager.GetString("NumberOfStarsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question order already in use, Try using another one..
        /// </summary>
        public static string OrderAlreadyInUse {
            get {
                return ResourceManager.GetString("OrderAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is required.
        /// </summary>
        public static string OrderRequired {
            get {
                return ResourceManager.GetString("OrderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Question doesn&apos;t exist, please refresh and try again..
        /// </summary>
        public static string QuestionDoesNotExistError {
            get {
                return ResourceManager.GetString("QuestionDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving failed, please try again..
        /// </summary>
        public static string SavingFailedError {
            get {
                return ResourceManager.GetString("SavingFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name.
        /// </summary>
        public static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name is required.
        /// </summary>
        public static string ServerNameRequired {
            get {
                return ResourceManager.GetString("ServerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Saved Successfully..
        /// </summary>
        public static string SettingsSavedMessage {
            get {
                return ResourceManager.GetString("SettingsSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLIDER.
        /// </summary>
        public static string SLIDER {
            get {
                return ResourceManager.GetString("SLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMILEY.
        /// </summary>
        public static string SMILEY {
            get {
                return ResourceManager.GetString("SMILEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please try again..
        /// </summary>
        public static string SomethingWentWrongError {
            get {
                return ResourceManager.GetString("SomethingWentWrongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STAR.
        /// </summary>
        public static string STAR {
            get {
                return ResourceManager.GetString("STAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Value.
        /// </summary>
        public static string StartValue {
            get {
                return ResourceManager.GetString("StartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Value Caption.
        /// </summary>
        public static string StartValueCaption {
            get {
                return ResourceManager.GetString("StartValueCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start value caption is required..
        /// </summary>
        public static string StartValueCaptionRequired {
            get {
                return ResourceManager.GetString("StartValueCaptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start value is required..
        /// </summary>
        public static string StartValueRequired {
            get {
                return ResourceManager.GetString("StartValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection was successful..
        /// </summary>
        public static string SuccessfulConnectionMessage {
            get {
                return ResourceManager.GetString("SuccessfulConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Questions Configurator.
        /// </summary>
        public static string SurveyQuestionsConfigurator {
            get {
                return ResourceManager.GetString("SurveyQuestionsConfigurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site is under maintenance, please refresh and try again..
        /// </summary>
        public static string TechnicalIssuesError {
            get {
                return ResourceManager.GetString("TechnicalIssuesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is required..
        /// </summary>
        public static string TextRequired {
            get {
                return ResourceManager.GetString("TextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id is required..
        /// </summary>
        public static string UserIdRequired {
            get {
                return ResourceManager.GetString("UserIdRequired", resourceCulture);
            }
        }
    }
}
